steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test
#steps:
#  - label: "Terraform Plan"
#    command: |
#      cd terraform/
#      terraform init
#      terraform plan

#  - label: "Terraform Apply"
#    command: |
#      cd terraform/
#      terraform apply -auto-approve
#      echo "Saving VM Public IP..."
#      terraform output -raw vm_public_ip > /tmp/vm_public_ip
#    depends_on: "Terraform Plan"

#  - label: "Run Ansible Playbook"
#    command: |
#      cd ansible/
      
#      # Retrieve the VM Public IP
#      export VM_IP=$(cat /tmp/vm_public_ip)
#      echo "VM Public IP: $VM_IP"
      
#      # Run Ansible with password authentication
#      ansible-playbook -i "$VM_IP," install_azure_cli.yml -u tommy --ask-pass --extra-vars "ansible_password=$ANSIBLE_PASSWORD"
#    depends_on: "Terraform Apply"
