steps:
  - label: "Terraform Plan"
    command: |
      cd terraform/
      terraform init
      terraform plan

  - label: "Terraform Apply"
    command: |
      cd terraform/
      terraform apply -auto-approve
    depends_on: "Terraform Plan"

  - label: "Run Ansible Playbook"
    command: |
      cd ansible/
      export vm_public_ip=$(terraform -chdir=../terraform output -raw vm_public_ip)
      echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
      chmod 600 ~/.ssh/id_ed25519
      ansible-playbook -i inventory.ini install_azure_cli.yml
    depends_on: "Terraform Apply"