steps:
  - label: "Terraform Init"
    key: "terraform-init"
    command: |
      cd terraform/
      terraform init
    artifact_paths:
      - "terraform/.terraform/**/*"
      - "terraform/.terraform.lock.hcl"
    plugins:
      - artifacts#v1.5.0:
          upload: "terraform/.terraform/**/*"
          upload: "terraform/.terraform.lock.hcl"

  - label: "Terraform Plan"
    key: "terraform-plan"
    command: |
      cd terraform/
      buildkite-agent artifact download "terraform/.terraform/**/*" .
      buildkite-agent artifact download "terraform/.terraform.lock.hcl" .
      terraform plan
    depends_on: "terraform-init"
    plugins:
      - artifacts#v1.5.0:
          download: "terraform/.terraform/**/*"
          download: "terraform/.terraform.lock.hcl"

  - label: "Terraform Apply"
    key: "terraform-apply"
    command: |
      cd terraform/
      terraform apply -auto-approve
    depends_on: "terraform-plan"

  - label: "Terraform Refresh"
    key: "terraform-refresh"
    command: |
      cd terraform/
      terraform refresh
    depends_on: "terraform-apply"

  - label: "Generate Inventory"
    key: "generate-inventory"
    command: |
      cd terraform/
      ./generate_inventory.sh
    depends_on: "terraform-refresh"

  - label: "Run Ansible Playbook"
    key: "run-ansible"
    command: |
      cd ansible/
      ansible-playbook -i inventory.ini install_azure_cli.yml
    depends_on: "generate-inventory"
