steps:
  - label: "Terraform Workflow"
    key: "terraform-workflow"
    command: |
      cd terraform/
      # Initialize Terraform
      echo "Running terraform init..."
      terraform init -input=false -no-color

      # Run Terraform plan
      echo "Running terraform plan..."
      terraform plan -input=false -no-color -out=tfplan


      # Apply Terraform changes
      echo "Running terraform apply..."
      terraform apply -input=false -no-color tfplan
    

      # Refresh the Terraform state
      echo "Running terraform refresh..."
      terraform refresh -input=false -no-color

      # Generate the inventory file
      echo "Generating inventory..."
      ./generate_inventory.sh

      # Run the Ansible playbook
      echo "Running Ansible playbook..."
      cd ../ansible/
      ansible-playbook -i inventory.ini install_azure_cli.yml
