steps:
  - label: "Terraform Init"
    key: "terraform-init"
    command: |
      cd terraform/
      echo "Running terraform init..."
      terraform init -input=false -no-color
      ls -la
      mv .terraform tmp/
      mv .terraform.lock.hcl tmp
      ls -la tmp/.terraform
      buildkite-agent artifact upload "tmp/.terraform/**" 
    artifact_paths:
      - "terraform/tmp/**"

  - label: "Terraform Plan"
    key: "terraform-plan"
    depends_on: "terraform-init"
    command: |
      cd terraform/
      echo "Downloading artifacts..."
      buildkite-agent artifact download "terraform/tmp/**" .
      ls -la tmp
      echo "Restoring .terraform and .terraform.lock.hcl..."
      mv tmp/.terraform .
      mv tmp/.terraform.lock.hcl .
      ls -la
      echo "Running terraform plan..."
      terraform plan -input=false -no-color -out=tfplan
    artifact_paths:
      - "terraform/tmp/**"

  - label: "Terraform Apply"
    key: "terraform-apply"
    depends_on: "terraform-plan"
    command: |
      cd terraform/
      buildkite-agent artifact download "terraform/.terraform/**" .  # Download .terraform directory
      buildkite-agent artifact download "terraform/.terraform.lock.hcl" .  # Download lock file
      
      echo "Running terraform apply..."
      terraform apply -input=false -no-color tfplan

  - label: "Terraform Refresh"
    key: "terraform-refresh"
    depends_on: "terraform-apply"
    command: |
      cd terraform/
      echo "Running terraform refresh..."
      terraform refresh -input=false -no-color

  - label: "Generate Inventory"
    key: "generate-inventory"
    depends_on: "terraform-refresh"
    command: |
      cd terraform/
      echo "Generating inventory..."
      ./generate_inventory.sh

  - label: "Run Ansible Playbook"
    key: "ansible-playbook"
    depends_on: "generate-inventory"
    command: |
      cd ansible/
      ansible-playbook -i inventory.ini install_azure_cli.yml
