steps:
  - label: "Terraform Init"
    key: "terraform-init"
    command: |
      cd terraform/
      echo "Running terraform init..."
      terraform init -input=false -no-color
      ls -la
      buildkite-agent artifact upload ".terraform/**/*"
      buildkite-agent artifact upload ".terraform.lock.hcl"

  - label: "Terraform Plan"
    key: "terraform-plan"
    depends_on: "terraform-init"
    command: |
      cd terraform/
      echo "Running terraform plan..."
      buildkite-agent artifact download ".terraform/**/*" .
      buildkite-agent artifact download ".terraform.lock.hcl" .
      chmod -R u+rx .terraform/providers/
      terraform plan -input=false -no-color -out=tfplan
      buildkite-agent artifact upload "tfplan"

  - label: "Terraform Apply"
    key: "terraform-apply"
    depends_on: "terraform-plan"
    command: |
      cd terraform/
      buildkite-agent artifact download ".terraform/**/*" .
      buildkite-agent artifact download ".terraform.lock.hcl" .
      buildkite-agent artifact download "tfplan" .
      chmod -R u+rx .terraform/providers/
      echo "Running terraform apply..."
      terraform apply -input=false -no-color tfplan

  - label: "Terraform Refresh"
    key: "terraform-refresh"
    depends_on: "terraform-apply"
    command: |
      cd terraform/
      echo "Running terraform refresh..."
      buildkite-agent artifact download ".terraform/**/*" .
      buildkite-agent artifact download ".terraform.lock.hcl" .
      buildkite-agent artifact download "tfplan" .
      chmod -R u+rx .terraform/providers/
      terraform refresh -input=false -no-color

  - label: "Generate Inventory"
    key: "generate-inventory"
    depends_on: "terraform-refresh"
    command: |
      cd terraform/
      echo "Generating inventory..."
      ./generate_inventory.sh

  - label: "Run Ansible Playbook"
    key: "ansible-playbook"
    depends_on: "generate-inventory"
    command: |
      cd ansible/
      ansible-playbook -i inventory.ini install_azure_cli.yml
